version: '3.8'
services:
  json-viewer:
    build: .
    container_name: json-viewer
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Uncomment below if you want to mount local code for live development
    # volumes:
    #   - .:/app
